// Generated by CoffeeScript 1.8.0
(function() {
  var Deadline;

  Deadline = (function() {
    function Deadline() {
      console.log('Deprecated. Use https://github.com/banterability/dateline instead.');
    }

    return Deadline;

  })();

  module.exports = Deadline;

}).call(this);
