// Generated by CoffeeScript 1.6.3
(function() {
  var Deadline, formatHours, formatMinutes, monthNames, topOfHour;

  Deadline = (function() {
    function Deadline(date) {
      this.date = date;
    }

    Deadline.prototype.getTime = function() {
      var hour, hours, minute, minutes, timeOfDay;
      hours = this.date.getHours();
      minutes = this.date.getMinutes();
      if (hours === 0 && minutes === 0) {
        return 'midnight';
      }
      if (hours === 12 && minutes === 0) {
        return 'noon';
      }
      timeOfDay = hours < 12 ? 'a.m.' : 'p.m.';
      hour = formatHours(hours);
      if (topOfHour(minutes)) {
        return "" + hour + " " + timeOfDay;
      }
      minute = formatMinutes(minutes);
      return "" + hour + ":" + minute + " " + timeOfDay;
    };

    Deadline.prototype.getDate = function() {
      var date, month, monthName, year;
      month = this.date.getMonth();
      date = this.date.getDate();
      year = this.date.getFullYear();
      monthName = monthNames[month];
      if (year === (new Date()).getFullYear()) {
        return "" + monthName + " " + date;
      }
      return "" + monthName + " " + date + ", " + year;
    };

    return Deadline;

  })();

  module.exports = Deadline;

  formatHours = function(hours) {
    if (hours === 0) {
      return 12;
    }
    if (hours > 12) {
      return hours - 12;
    }
    return hours;
  };

  topOfHour = function(minutes) {
    return minutes === 0;
  };

  formatMinutes = function(minutes) {
    if (minutes < 10) {
      return "0" + minutes;
    }
    return minutes;
  };

  monthNames = ['Jan.', 'Feb.', 'March', 'April', 'May', 'June', 'July', 'Aug.', 'Sept.', 'Oct.', 'Nov.', 'Dec.'];

}).call(this);
